name: API Tests CI

on: [push, pull_request]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 15
        uses: actions/setup-java@v4
        with:
          java-version: '15'
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean test

      - name: Publish JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
